export const maxHp = 6;
export const numLevels = 10;
export const numTiles = 16;
export const startingHp = 3;
export const tileRenderSizePX = 48;             // px
export const refreshRate = 1000 / 60;   // 60 frames per second
export const imgAssetPath = "assets/images/";
export const sfxAssetPath = "assets/sounds/"
export const alternateSpriteTimeMS = 600;
